version: '3.9'

networks:
  dev_org_net:

services:

  web:
    container_name: nginx-1.25_php-8.2
    build: .
    volumes:
      - ./config/web/log:/var/log/nginx/
      - ./src:/var/www/dev.org/html/public
    ports:
      - "${APP_PORT}:80"
      - "${APP_TLS_PORT}:443"
    networks:
      - dev_org_net

